### ISSUE TITLE
lab.operations.html in ch3 has Uncaught DOMException

### ISSUE THREAD

**Issue by vk8051** [AurelioDeRosa/jquery-in-action#4]
input $("img").hide(); and press Execute button will show error below

lab.operations.html:185 Uncaught DOMException: Blocked a frame with origin "null" from accessing a cross-origin frame.
    at HTMLFormElement.<anonymous> (file:///C:/Users/vince/Downloads/jquery-in-action-master/chapter-3/lab.operations.html:185:30)
    at HTMLFormElement.dispatch (file:///C:/Users/vince/Downloads/jquery-in-action-master/js/jquery-1.11.3.min.js:4:8549)
    at HTMLFormElement.r.handle (file:///C:/Users/vince/Downloads/jquery-in-action-master/js/jquery-1.11.3.min.js:4:5252)
(anonymous) @ lab.operations.html:185
dispatch @ jquery-1.11.3.min.js:4
r.handle @ jquery-1.11.3.min.js:4

**Comment by AurelioDeRosa** [comment]
Hi. Have you tried to follow the instructions at the bottom of page 56?

**Comment by vk8051** [comment]
I review the book bottom of page 57 in chinese version.
I realized what you meant.
thank you.

**Comment by AurelioDeRosa** [comment]
Glad you solved. Closing.
